# Generated by Django 6.1.1 on 2026-09-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('MARCA', 'Guía de Marca'), ('INICIO', 'Página de Inicio'), ('SERVICIOS', 'Servicios / Productos'), ('BLOG', 'Entrada de Blog'), ('CONTACTO', 'Contacto')], max_length=50, unique=True)),
                ('drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('content_payload', models.JSONField(default=dict, help_text='Datos JSON procesados desde Drive')),
                ('status', models.CharField(choices=[('BORRADOR_IA', 'Borrador IA'), ('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PUBLICADO', 'Publicado')], default='BORRADOR_IA', max_length=30)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_sections',
            },
        ),
    ]
