# Generated by Django 6.1.1 on 2026-09-28 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsection',
            name='drive_file_id',
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='content_payload',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='section_key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='status',
            field=models.CharField(choices=[('BORRADOR_IA', 'Borrador IA'), ('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('PUBLICADO', 'Publicado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterModelTable(
            name='contentsection',
            table=None,
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('BOTH', 'Ambas')], max_length=20)),
                ('copy_text', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BORRADOR_IA', 'Borrador IA'), ('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado para Publicar'), ('PUBLICADO', 'Publicado en Meta')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
