# Generated by Django 6.1.1 on 2026-10-01 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_contentsection_drive_file_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialpost',
            name='approved_by',
        ),
        migrations.CreateModel(
            name='ManagedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('PAGINA', 'Página Web (Sección)'), ('BLOG', 'Entrada de Blog'), ('REDES', 'Redes Sociales')], default='BLOG', max_length=20)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('drive_file_id', models.CharField(help_text='ID original del archivo en Google Drive', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador IA'), ('PENDING', 'Pendiente de Aprobación'), ('APPROVED', 'Aprobado'), ('PUBLISHED', 'Publicado')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ContentSection',
        ),
        migrations.DeleteModel(
            name='SocialPost',
        ),
    ]
